### ISSUE TITLE
Transaction fee with decimals fails

### ISSUE THREAD

**Issue by JaimeSilver** [hashingsystems/hash.js#15]
When you type a transaction fee with decimals, and submit a Smart Contract call, it fails with a type missmatch error.

![hashing 1](https://user-images.githubusercontent.com/44205395/70061222-e4308080-15b1-11ea-8664-d8c038c3820b.jpg)
![hashing 2](https://user-images.githubusercontent.com/44205395/70061221-e4308080-15b1-11ea-8773-76d287c13fbe.jpg)
![hashing 3](https://user-images.githubusercontent.com/44205395/70061220-e397ea00-15b1-11ea-9e44-bc1d7f1c60f5.jpg)

**Comment by publu** [comment]
There's an issue with the conversion from type. Let's see what we can do to fix it

**Comment by publu** [comment]
Fixed on v1.4^
