### ISSUE TITLE
error in payment

### ISSUE THREAD

**Issue by publicocean0** [hashingsystems/hash.js#4]
i have error to fix . But in dont understand how works mps . It create a inside tag in html. But i dont see how it is completing payment. No call to external servers. Actually using checktransaction give me always no result . MPS-JS starting is OK . <hedera-micropayment data-submissionnode= '0.0.11' , 
data-paymentserver= 'https://mps.hashingsystems.com/' , 
data-recipientlist= '[{ "to": "0.0.3", "tinybars": 1 }]' , 
data-contentid= 'a5fcac96-706b-4106-8b26-53ce7613b2b6' , 
data-type= 'order' , 
data-memo= 'a5fcac96-706b-4106-8b26-53ce7613b2b6' , 
data-extensionid= 'ligpaondaabclfigagcifobaelemiena' , 
data-redirect= '{ "nonPayingAccount": "/insufficient-amount/", "noAccount": "/account-not-paired/", "homePage": "/"}' , 
data-time= '1564243340676' , 
></hedera-micropayment>
main.js:38 MPS-JS started {paymentserver: "https://mps.hashingsystems.com/", extensionid: "ligpaondaabclfigagcifobaelemiena", error: "/no-extension", type: "order", time: 1564243340676, …}
main.js:73 detect: user has extension installed
mw inti seams create to request but is not submiting it .

**Comment by publu** [comment]
Can you check the Hedera extension for more insight? 

You can test it by going to https://mps.hashingsystems.com/

If you receive an error, make sure you have allowed the page to pay requests via the chrome extension.

See here:
<img width="328" alt="Screen Shot 2019-07-30 at 4 18 16 PM" src="https://user-images.githubusercontent.com/4308462/62178691-ac54bc00-b2e5-11e9-8473-110c8554b8fb.png">

**Comment by publicocean0** [comment]
yes chrome extension is working , i had tested it.  There are many strange behaviors. . For example if i install the library in a global script tag ... it is not producing also the <hedera-micropayment tag. I copied a example there all is inside a subrutine. In this case i have the behavior above.

**Comment by publicocean0** [comment]
I tested also this https://github.com/hashingsystems/hashgraph-bidding-example . It is not working . It show always the old rows.
